<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <EnableNETAnalyzers>True</EnableNETAnalyzers>
        <UseAppHost>false</UseAppHost>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(CODESPACES)' == 'true' or '$(GITHUB_ACTIONS)' == 'true' or '$(WEBSITE_SITE_NAME)' != '' ">
<!--
"...format=%%cI...", see Ed.Common.targets, works only under Windows locally.
Correct it to %cI on GitHub Codespaces / Actions and Azure DevOps pipelines.
See output below in target RestoreClientSideLibraries.
-->
        <LatestCommitTimestampScript><![CDATA[git log -1 --format=%cI]]></LatestCommitTimestampScript>

    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <!-- Enable release-version debugging (optimization off, etc.) -->
        <Optimize>False</Optimize>
    </PropertyGroup>
    
    <Import Project="$(MSBuildThisFileDirectory)..\msbuildLib\Ed.Common.props" />
    <Import Project="$(MSBuildThisFileDirectory)..\msbuildLib\Ed.CSharp.targets" />

    <ItemGroup>
      <ProjectReference Include="..\DeviceControllerLib\DeviceControllerLib.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MongoDB.Driver" Version="3.11.0" />
      <PackageReference Include="System.IO.Hashing" Version="10.0.11" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Properties\PublishProfiles\" />
      <Folder Include="Properties\ServiceDependencies\" />
      <Folder Include="Settings\" />
    </ItemGroup>

    <Target Name="RestoreClientSideLibraries" BeforeTargets="Build">
        <Exec Command="libman restore" />
        <Message Importance="high" text="Environment: CODESPACES=&gt;'$(CODESPACES)', GITHUB_ACTIONS=&gt;'$(GITHUB_ACTIONS)', WEBSITE_SITE_NAME=&gt;'$(WEBSITE_SITE_NAME)', RUNNER_OS=&gt;'$(RUNNER_OS)'." />

    </Target>

</Project>